export const ONBOARDING_CONFIG = {
  TOTAL_STEPS: 22,
  STEPS: {
    WELCOME: 1,
    HEART_RISK: 2,
    LUNG_RISK: 3,
    OTHER_RISK: 4,
    DAILY_COST: 5,
    ANNUAL_COST: 6,
    TEN_YEAR_COST: 7,
    TWENTY_YEAR_COST: 8,
    TRAVEL_EXPERIENCE: 9,
    WANTS_HOBBIES: 10,
    INVESTMENT: 11,
    FAMILY: 12,
    PASSIVE_SMOKING: 13,
    APPEARANCE_IMPACT: 14,
    SOCIAL_CONSTRAINTS: 15,
    QUESTIONNAIRE: 16,
    MOTIVATION: 17,
    CIGARETTES: 18,
    PRICE: 19,
    PACK_SIZE: 20,
    READY: 21,
    SUPPORT: 22,
  },
} as const;

export type OnboardingStep =
  (typeof ONBOARDING_CONFIG.STEPS)[keyof typeof ONBOARDING_CONFIG.STEPS];
